name: CI pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install pipenv
      run: pip install pipenv

    - name: Install dependencies
      run: |
        pipenv install

    - name: Run unit tests
      run: |
        pipenv run python -m unittest discover -s tests -v
